name: iesce_invigilation
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.5.0

  supabase_flutter: ^2.5.0

  # UI / Icons
  cupertino_icons: ^1.0.8

  # File system access
  path_provider: ^2.1.5

  # Calendar / Scheduling
  syncfusion_flutter_calendar: ^29.1.38
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
